apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:

      - name: product-service
<<<<<<< HEAD
        image: andy2025/product-service:c2852b8
=======
        image: andy2025/product_service:15e46d7
>>>>>>> df287ce8cc727088f0159549f23b5ba85147e24c
        ports:
        - containerPort: 8081

        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://${DB_ENDPOINT}:5432/${DB_NAME}"

          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username

          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
